//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace applicationFiltre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LO_zu_ART
    {
        public int Lagerort_ID { get; set; }
        public int Artikel_ID { get; set; }
        public double Menge { get; set; }
        public short PlatzTyp { get; set; }
        public string ChargenNr { get; set; }
        public Nullable<System.DateTime> IVDatum { get; set; }
        public Nullable<int> Benutzer_ID { get; set; }
        public double ReservIn { get; set; }
        public double ReservOut { get; set; }
        public Nullable<int> Kostenstelle_ID { get; set; }
        public Nullable<System.DateTime> Haltbardatum { get; set; }
        public Nullable<System.DateTime> ErzeugungsDatum { get; set; }
        public Nullable<System.DateTime> BewegungsDatum { get; set; }
        public byte LOGesperrt { get; set; }
        public string LOSperrgrund { get; set; }
        public Nullable<System.DateTime> LagerDatum { get; set; }
        public Nullable<int> Werkzeug_ID { get; set; }
        public Nullable<double> MaxBestand { get; set; }
        public int Regal_ID { get; set; }
        public int Fachboden_ID { get; set; }
        public int Einteilung_ID { get; set; }
        public int Position { get; set; }
        public int Tiefe { get; set; }
        public Nullable<short> FBefehl_CAR { get; set; }
        public string Artikel { get; set; }
        public int Platzgr_ID { get; set; }
        public Nullable<double> AutoInventur { get; set; }
        public Nullable<int> Sequencenumber { get; set; }
        public string Zonen { get; set; }
    }
}
