//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace applicationFiltre.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PP5000Entities : DbContext
    {
        public PP5000Entities()
            : base("name=PP5000Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ORDERS> ORDERS { get; set; }
        public DbSet<POSITIONS> POSITIONS { get; set; }
        public DbSet<ybPositionsTransporteur2> ybPositionsTransporteur2 { get; set; }
    }
}
