//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace applicationFiltre.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class WMSEntities : DbContext
    {
        public WMSEntities()
            : base("name=WMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ORDERS> ORDERS { get; set; }
        public DbSet<POSITIONS> POSITIONS { get; set; }
    
        public virtual ObjectResult<GetOrders_Result> GetOrders(string typeCommande, string centrale)
        {
            var typeCommandeParameter = typeCommande != null ?
                new ObjectParameter("typeCommande", typeCommande) :
                new ObjectParameter("typeCommande", typeof(string));
    
            var centraleParameter = centrale != null ?
                new ObjectParameter("centrale", centrale) :
                new ObjectParameter("centrale", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrders_Result>("GetOrders", typeCommandeParameter, centraleParameter);
        }
    }
}
