//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace applicationFiltre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public string ORDERS1 { get; set; }
        public string ORDERSCOL { get; set; }
        public int TYPETRANSACTION { get; set; }
        public string ORDERCLIENT { get; set; }
        public Nullable<int> COLISAGE { get; set; }
        public Nullable<int> URGENT { get; set; }
        public string TYPEBL { get; set; }
        public string NOMCOLIS { get; set; }
        public string CONSIGNE1 { get; set; }
        public string CONSIGNE2 { get; set; }
        public string CODECLIENTLIVRE { get; set; }
        public string RS1 { get; set; }
        public string ADR11 { get; set; }
        public string ADR12 { get; set; }
        public string CP1 { get; set; }
        public string VILLE1 { get; set; }
        public string PAYS1 { get; set; }
        public string CODECLIENTFACTURE { get; set; }
        public string RS2 { get; set; }
        public string ADR21 { get; set; }
        public string ADR22 { get; set; }
        public string CP2 { get; set; }
        public string VILLE2 { get; set; }
        public string PAYS2 { get; set; }
        public string CODETRANSPORTEUR { get; set; }
        public string COMMENTAIRE1 { get; set; }
        public string COMMENTAIRE2 { get; set; }
        public string COMMENTAIRE3 { get; set; }
        public string COMMENTAIRE4 { get; set; }
        public Nullable<double> MONTANT1 { get; set; }
        public Nullable<double> MONTANT2 { get; set; }
        public Nullable<double> MONTANT3 { get; set; }
        public Nullable<double> MONTANT4 { get; set; }
        public Nullable<double> MONTANT5 { get; set; }
        public string GESTIONSAGE { get; set; }
        public Nullable<double> POIDSCOLIS { get; set; }
        public Nullable<int> ETAT { get; set; }
        public string CompteExtand { get; set; }
        public string Emballage { get; set; }
        public Nullable<System.DateTime> DateHeureFichier { get; set; }
        public string UtilisateurControle { get; set; }
        public Nullable<System.DateTime> DateHeureControle { get; set; }
        public Nullable<System.DateTime> ORD_D_CREATE { get; set; }
        public string NOMCLIENTFINAL { get; set; }
        public string DateCommandeX3 { get; set; }
        public string HeureCommandeX3 { get; set; }
        public string CentraleX3 { get; set; }
        public string NbLigneCmdX3 { get; set; }
        public string TransporteurX3 { get; set; }
        public string ModeLivraisonX3 { get; set; }
        public string PrioriteLivraisonX3 { get; set; }
        public string PoidsNetX3 { get; set; }
        public string CmdAvecRX { get; set; }
        public Nullable<int> PackagingX3 { get; set; }
        public string InfoX3_1 { get; set; }
        public string InfoX3_2 { get; set; }
        public Nullable<int> InfoX3_3 { get; set; }
        public string DateDescente { get; set; }
        public string HeureDescente { get; set; }
        public string PreAxe { get; set; }
    }
}
