//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace applicationFiltre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passerelle
    {
        public int EnregUnique { get; set; }
        public Nullable<int> PasserelleActive { get; set; }
        public Nullable<int> IntervalleTraitement { get; set; }
        public string RepImpCommandes { get; set; }
        public string RepImpAnnulations { get; set; }
        public string RepImpReceptions { get; set; }
        public Nullable<int> MaxFichiersImport { get; set; }
        public string RepImpPP5000 { get; set; }
        public Nullable<int> ExporterSortiesUnitaires { get; set; }
        public Nullable<int> ExporterEntreesUnitaires { get; set; }
        public Nullable<int> ExporterCorrectionsDeStock { get; set; }
        public string RepExpReceptions { get; set; }
        public string RepExpEntreesUnitaires { get; set; }
        public string RepExpSortiesUnitaires { get; set; }
        public Nullable<int> NiveauLog { get; set; }
        public string CheminFichierLog { get; set; }
        public Nullable<int> TailleMaxFichierLog { get; set; }
        public Nullable<int> HistoriserFichiersHost { get; set; }
        public string RepHistoriqueHost { get; set; }
        public Nullable<int> HistoriserFichiersPP5000 { get; set; }
        public string RepHistoriquePP5000 { get; set; }
        public Nullable<int> PrioriteReserveMaxLignes { get; set; }
        public Nullable<int> PrioriteReserveMaxQtes { get; set; }
        public Nullable<System.DateTime> DerniereLecture { get; set; }
        public string ServerSocket_PC { get; set; }
        public Nullable<int> ServerSocket_Port { get; set; }
    }
}
