//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace applicationFiltre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITIONS
    {
        public int TYPETRANSACTION { get; set; }
        public string ORDERS { get; set; }
        public int NUMEROLIGNE { get; set; }
        public string ARTICLE { get; set; }
        public string DESIGNATION1 { get; set; }
        public string DESIGNATION2 { get; set; }
        public Nullable<int> QUANTITE { get; set; }
        public string INFO1 { get; set; }
        public string INFO2 { get; set; }
        public string INFO3 { get; set; }
        public string INFO4 { get; set; }
        public string INFO5 { get; set; }
        public string INFO6 { get; set; }
        public Nullable<int> ETAT { get; set; }
        public string CHECKED { get; set; }
        public Nullable<System.DateTime> DATEI { get; set; }
        public string ZTYPACH { get; set; }
        public string POHNUM { get; set; }
        public Nullable<int> POPLIN { get; set; }
        public byte IdTypePosition { get; set; }
        public Nullable<int> QUANTITERECU { get; set; }
        public string INFO7 { get; set; }
    }
}
