//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace applicationFiltre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITIONS
    {
        public int TYPETRANSACTION { get; set; }
        public string ORDERS { get; set; }
        public string ORDERSCOL { get; set; }
        public int NUMEROLIGNE { get; set; }
        public string ARTICLE { get; set; }
        public Nullable<int> ASERVIR { get; set; }
        public Nullable<int> ACOLISER { get; set; }
        public string RELIQUAT { get; set; }
        public string ARTICLECLIENT { get; set; }
        public string DESIGNATION1 { get; set; }
        public string DESIGNATION2 { get; set; }
        public Nullable<double> QUANTITE { get; set; }
        public Nullable<double> PRIX1 { get; set; }
        public Nullable<double> PRIX2 { get; set; }
        public string INFO1 { get; set; }
        public string INFO2 { get; set; }
        public string INFO3 { get; set; }
        public string INFO4 { get; set; }
        public string INFO5 { get; set; }
        public string INFO6 { get; set; }
        public string INFO7 { get; set; }
        public Nullable<double> POIDSUNITAIRE { get; set; }
        public Nullable<double> POIDSLIGNE { get; set; }
        public Nullable<double> PGTAILLE { get; set; }
        public Nullable<double> VOLUMEUNITAIRE { get; set; }
        public Nullable<double> VOLUMELIGNE { get; set; }
        public Nullable<double> MAXQUANT { get; set; }
        public Nullable<double> PACKMENGE { get; set; }
        public Nullable<double> RESBESTAND { get; set; }
        public Nullable<int> NUMCOLIS { get; set; }
        public Nullable<int> NBCOLIS { get; set; }
        public string NOMCOLIS { get; set; }
        public Nullable<int> ETAT { get; set; }
        public string CHECKED { get; set; }
        public Nullable<System.DateTime> DATEI { get; set; }
        public int ID { get; set; }
        public string ZTYPACH { get; set; }
        public string POHNUM { get; set; }
        public Nullable<int> POPLIN { get; set; }
    }
}
